### ISSUE TITLE
how the heck do i use this ?

### ISSUE THREAD

**Issue by hayden-t** [fgm/beanstalk-munin-php#2]
So i have it on my servers with composer and pheanstalk, and tried adding the plugins folder to munin, htat dont work,  i tried running a plugin file by itself, that doesnt work, the paths are wrong, your include of autoload does not get out of the current dir structure to be able to get into vendor dir... so i tried changing this but still not luck, complains about base plugin class missing. now i see this is a file in src. so not really sure the correct way to use this. thanks

**Comment by fgm** [comment]
If you just cloned the repo, you need to run a "composer install" so that composer builds the autoloader in vendor/autoload.php where the plugins will find the autoloader

Note that this was written for the version of Munin that was current 4 years ago. Which version are you currently using ? And which version of PHP ?

**Comment by fgm** [comment]
I just added an `INSTALL.md` file for issue #3, which should provide all the info needed. Can you confirm this allows you to solve your problem, and close the issue if it does ?

[INSTALL.md](/fgm/beanstalk-munin-php/blob/master/INSTALL.md)

**Comment by hayden-t** [comment]
i only have munin 1.4 under whm, have tried it anyway and get this error, ive requested 2.x , will see if can get it

2018/08/13-11:20:02 [8898] Error output from bs_cmd_rate.php:
2018/08/13-11:20:02 [8898]      Can't exec "/etc/munin/plugins/bs_cmd_rate.php": Permission denied at /usr/local/cpanel/3rdparty/perl/522/lib/perl5/cpanel_lib/Munin/Node/Service.pm line 215, <STDIN> line 7.
2018/08/13-11:20:02 [8898]      # ERROR: Failed to exec.
2018/08/13-11:20:02 [8898] Service 'bs_cmd_rate.php' exited with status 42/0.
2018/08/13-11:20:02 [8898] Error output from bs_cmd_rate.php:
2018/08/13-11:20:02 [8898]      Can't exec "/etc/munin/plugins/bs_cmd_rate.php": Permission denied at /usr/local/cpanel/3rdparty/perl/522/lib/perl5/cpanel_lib/Munin/Node/Service.pm line 215, <STDIN> line 8.
2018/08/13-11:20:02 [8898]      # ERROR: Failed to exec.
2018/08/13-11:20:02 [8898] Service 'bs_cmd_rate.php' exited with status 42/0.

**Comment by hayden-t** [comment]
ok, so i only have munin 1.4 but i think i have it working, i had to change the top of php files to say
#!/usr/bin/env php-cli
to stop headers from being posted and interfering with the response. eg
fetch bs_cmd_rate.php
X-Powered-By: PHP/5.5.38
Content-type: text/html
cmd_put.value 2598
cmd_reserve.value 2468
cmd_reserve_timeout.value 0
cmd_delete.value 2580
cmd_touch.value 0
cmd_release.value 0
cmd_bury.value 20

 i also had to add this to munin plugin conf
[bs_*]
user root
group root

**Comment by hayden-t** [comment]
its working ! i got all the pretty lines :) (btw this is even under whm/centos)

**Comment by fgm** [comment]
Congratulations! Thanks for the details: these changes may be helpful to others too. This seems to be a peculiar PHP configuration: I had never seen headers been sent before from the php CLI even when not called "php-cli", so it must be a whm/centos thing.

From [this SO issue](https://stackoverflow.com/questions/2443575/how-could-i-stop-php-from-returning-headers-when-executed-from-commandline), it seems your system is configured to run PHP CGI when called from the CLI, so <del>maybe changing the shebang from "php" (as in master) to "php -q" instead of "php-cli" (as you did) would also work, in which case the same would also work on Debian versions using the CLI version instead of using the CGI version for CLI. Could you try it ?</del> doesn't work on most systems, behavior is not specified in Posix.

Strange that you still have Munin 1.4, BTW: this is a 2009 version, while 2.0 was introduced in 2011 and is the current stable branch.

**Comment by hayden-t** [comment]
tried -q first but crashes. you are right about the cgi vs cli thing as also in cron i had to stipulate php-cli to get the result i wanted. now if this is just something host specific or whm/cpanel specific or centos 6 specific im not sure, normally i use debian too, as for the 1.4 thing its just what the hosts put on it as a plugin for whm when i had trouble with system performance and was trying to track it down. once again maybe to do with my version of centos/whm or host, but regardless, got it working, which is great ! thanks again for porting this.

**Comment by fgm** [comment]
You're welcome.
