### ISSUE TITLE
TUBES variable where ?

### ISSUE THREAD

**Issue by hayden-t** [fgm/beanstalk-munin-php#5]
Hi, ive tried putting  "env.TUBES request" in /etc/munin/plugin-conf.d/cpanel.conf but its not working, have i got the method and location correct ?

**Comment by fgm** [comment]
Sorry, I'm not familiar with CPanel. This plugin works on its own, automatically adding a bunch of Beanstalkd graphs to your Munin config, without needing to be declared in another tool beyond core Munin. 

The place where it uses the TUBES environment variable is in the QueueAge class, where it is used to initialize the `bs_queue_age` plugin so that it reports on a specific set of tubes (space-separated string), defaulting to just `default`.

**Comment by hayden-t** [comment]
im just trying to work otu how to set that variable ? i can always hard code it, but is 'env.TUBES tubname' correct

**Comment by fgm** [comment]
in bash, it would just be `export TUBES="some_tube some_other_tube"`. No idea how to do it from cpanel.conf, regrettably.

**Comment by hayden-t** [comment]
so looking at the code, it seems to if not set just supply 'default' tube , but my graphs show all

**Comment by fgm** [comment]
Strange: as you can see in `QueueAgePlugin::data()`, it only reports on the initialized tubes by looping on `$this->tubes`, and that property is initialized in `createFromGlobals`. You might debug it by checking what munin-node shows using `telnet localhost munin`.

**Comment by fgm** [comment]
Do you have need more info ? Or can you close this issue ?

**Comment by hayden-t** [comment]
if i telnet and run fetch bs_queue_size.php it reports on all tubes

**Comment by hayden-t** [comment]
so i put a echo $tubes in bs_queue_age.php line 34 and when i run that plugin in actually reports my tube name set via 'env.TUBES tubname'  so likey that plugin is only reporting on that tube, but why to none of the other plugins have a createFromGlobals function that sets the queues to watch ?

**Comment by fgm** [comment]
Outdated question: please reopen if still applicable.
